------------------------------------------------------------------------------------------------------------------------

[2014-09-29 08:25:24 #1 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' has been recovered (tr. 1-4)

[2014-09-29 08:25:24 #2 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is opened by 7184@jmpicadow7

[2014-09-29 08:25:58 #3 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is closed by 7184@jmpicadow7

------------------------------------------------------------------------------------------------------------------------

[2014-09-29 08:27:14 #1 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' has been recovered (tr. 1-4)

[2014-09-29 08:27:14 #2 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is opened by 10844@jmpicadow7

[2014-09-29 08:27:41 #3 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is closed by 10844@jmpicadow7

------------------------------------------------------------------------------------------------------------------------

[2014-09-29 08:31:49 #1 explorer] 
[ObjectDB 2.5.6_05] javax.persistence.PersistenceException
Attempt to open a database file 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.O(LFL.java:916)
	at com.objectdb.o.LFL.I(LFL.java:862)
	at com.objectdb.o.LFL.I(LFL.java:772)
	at com.objectdb.o.SFL.<init>(SFL.java:232)
	at com.objectdb.o.MST.<init>(MST.java:117)
	at com.objectdb.o.MST.aK(MST.java:99)
	at com.objectdb.o.MSF.UP(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:743)
	at com.objectdb.jpa.EMF.an(EMF.java:238)
	at com.objectdb.o.OMF.am(OMF.java:684)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:257)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2014-09-29 10:58:48 #1 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is opened by 11672@jmpicadow7

[2014-09-29 11:03:44 #2 store] 
Database 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' is closed by 11672@jmpicadow7

------------------------------------------------------------------------------------------------------------------------

[2014-09-29 14:21:29 #1 explorer] 
[ObjectDB 2.5.6_05] javax.persistence.PersistenceException
Attempt to open a database file 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'D:\projects\Ahorro\SAMMS\projects\SAMMS_MIG_REPOSITORIO\Proyectos_Auxiliares\SAMMS_ControlM\data\controlm.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.O(LFL.java:916)
	at com.objectdb.o.LFL.I(LFL.java:862)
	at com.objectdb.o.LFL.I(LFL.java:772)
	at com.objectdb.o.SFL.<init>(SFL.java:232)
	at com.objectdb.o.MST.<init>(MST.java:117)
	at com.objectdb.o.MST.aK(MST.java:99)
	at com.objectdb.o.MSF.UP(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:743)
	at com.objectdb.jpa.EMF.an(EMF.java:238)
	at com.objectdb.o.OMF.am(OMF.java:684)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:257)
	... 17 more

